export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCESS';
export const GET_ARTISTS_FAIL = 'GET_ARTISTS_FAIL';
export const GET_ARTISTS_ALBUMS_SUCCESS = 'GET_ARTISTS_ALBUMS_SUCESS';
export const GET_ARTISTS_ALBUMS_FAIL = 'GET_ARTISTS_ALBUMS_FAIL';
export const GET_ALBUM_PHOTOS_SUCCESS = 'GET_ALBUM_PHOTOS_SUCESS';
export const GET_ALBUM_PHOTOS_FAIL = 'GET_ALBUM_PHOTOS_FAIL';
export const SET_LOADING = 'SET_LOADING';
